using backend.DTOs;
using backend.Services.AdminServices;
using Backend.Tests.Infra;
using FluentAssertions;

namespace Backend.Tests;

public class AdminServicesTests
{
    // --- CREATE ---

    [Fact]
    public void CreateAdmin_Creates_Admin_And_Maps_To_ReadDto()
    {
        var (ctx, conn) = TestDbFactory.CreateSqliteInMemoryContext();
        try
        {
            var svc = new AdminServices(ctx);

            // Assumes your CreateAdminDto has these fields (adjust if needed)
            var input = new CreateAdminDto(
                Email: "new@admin.com",
                FirstName: "New",
                LastName: "Admin",
                AdminPassword: "Secret123!"
            );

            var result = svc.CreateAdmin(input);

            result.Should().NotBeNull("service should return a DTO when creation succeeds");
            result!.Email.Should().Be("new@admin.com");

            var stored = ctx.Users.Single(u => u.Email == "new@admin.com");
            stored.Role.Should().Be("admin", "service should force 'admin' role on creation");
            stored.Id.Should().BeGreaterThan(0, "Id should be generated by DB");
        }
        finally { conn.Dispose(); }
    }

    // --- READ ONE ---

    [Fact]
    public void ReadAdmin_Returns_Null_When_Not_Found()
    {
        var (ctx, conn) = TestDbFactory.CreateSqliteInMemoryContext();
        try
        {
            var svc = new AdminServices(ctx);

            var dto = svc.ReadAdmin(id: 999);

            dto.Should().BeNull("no user with this id exists");
        }
        finally { conn.Dispose(); }
    }

    [Fact]
    public void ReadAdmin_Returns_Null_When_User_Is_Not_Admin()
    {
        var (ctx, conn) = TestDbFactory.CreateSqliteInMemoryContext();
        try
        {
            ctx.Users.Add(Seed.Regular(email: "user@x.com"));
            ctx.SaveChanges();

            var svc = new AdminServices(ctx);
            var id = ctx.Users.Single().Id;

            var dto = svc.ReadAdmin(id);

            dto.Should().BeNull("non-admin should not be returned by ReadAdmin");
        }
        finally { conn.Dispose(); }
    }

    [Fact]
    public void ReadAdmin_Returns_Dto_For_Admin()
    {
        var (ctx, conn) = TestDbFactory.CreateSqliteInMemoryContext();
        try
        {
            ctx.Users.Add(Seed.Admin(email: "admin@x.com"));
            ctx.SaveChanges();

            var svc = new AdminServices(ctx);
            var id = ctx.Users.Single().Id;

            var dto = svc.ReadAdmin(id);

            dto.Should().NotBeNull();
            dto!.Email.Should().Be("admin@x.com");
        }
        finally { conn.Dispose(); }
    }

    // --- READ MANY ---

    [Fact]
    public void ReadAdmins_Returns_Only_Admins()
    {
        var (ctx, conn) = TestDbFactory.CreateSqliteInMemoryContext();
        try
        {
            ctx.Users.AddRange(
                Seed.Admin(email: "a1@x.com"),
                Seed.Regular(email: "u1@x.com"),
                Seed.Admin(email: "a2@x.com")
            );
            ctx.SaveChanges();

            var svc = new AdminServices(ctx);

            var list = svc.ReadAdmins();

            list.Should().HaveCount(2, "should only return admins");
            list.Select(x => x.Email).Should().BeEquivalentTo(new[] { "a1@x.com", "a2@x.com" });
        }
        finally { conn.Dispose(); }
    }

    // --- UPDATE ---

    [Fact]
    public void UpdateAdmin_Returns_False_When_Not_Found()
    {
        var (ctx, conn) = TestDbFactory.CreateSqliteInMemoryContext();
        try
        {
            var svc = new AdminServices(ctx);

            var ok = svc.UpdateAdmin(12345, new UpdateAdminDto(
                Email: "x@x.com",
                FirstName: "X",
                LastName: "Y"
            ));

            ok.Should().BeFalse("cannot update a non-existent user");
        }
        finally { conn.Dispose(); }
    }

    [Fact]
    public void UpdateAdmin_Returns_False_When_User_Not_Admin()
    {
        var (ctx, conn) = TestDbFactory.CreateSqliteInMemoryContext();
        try
        {
            ctx.Users.Add(Seed.Regular(email: "user@x.com"));
            ctx.SaveChanges();

            var user = ctx.Users.Single();
            var svc = new AdminServices(ctx);

            var ok = svc.UpdateAdmin(user.Id, new UpdateAdminDto(
                Email: "changed@x.com",
                FirstName: null,
                LastName: null
            ));

            ok.Should().BeFalse("service should block updates for non-admin users");
        }
        finally { conn.Dispose(); }
    }

    [Fact]
    public void UpdateAdmin_Updates_Only_NonEmpty_Fields_And_Persists()
    {
        var (ctx, conn) = TestDbFactory.CreateSqliteInMemoryContext();
        try
        {
            ctx.Users.Add(Seed.Admin(email: "old@x.com", first: "Old", last: "Name"));
            ctx.SaveChanges();

            var admin = ctx.Users.Single();
            var svc = new AdminServices(ctx);

            var ok = svc.UpdateAdmin(admin.Id, new UpdateAdminDto(
                Email: "new@x.com",  // change
                FirstName: "  ",     // whitespace -> ignore
                LastName: null      // null -> ignore
            ));

            ok.Should().BeTrue();

            var reloaded = ctx.Users.Find(admin.Id)!;
            reloaded.Email.Should().Be("new@x.com", "non-empty Email should be applied");
            reloaded.FirstName.Should().Be("Old", "whitespace should be ignored");
            reloaded.LastName.Should().Be("Name", "null should be ignored");
        }
        finally { conn.Dispose(); }
    }

    // --- DELETE ---

    [Fact]
    public void DeleteAdmin_Returns_False_When_Not_Found()
    {
        var (ctx, conn) = TestDbFactory.CreateSqliteInMemoryContext();
        try
        {
            var svc = new AdminServices(ctx);

            var ok = svc.DeleteAdmin(888);

            ok.Should().BeFalse("cannot delete non-existent user");
        }
        finally { conn.Dispose(); }
    }

    [Fact]
    public void DeleteAdmin_Returns_False_When_User_Not_Admin()
    {
        var (ctx, conn) = TestDbFactory.CreateSqliteInMemoryContext();
        try
        {
            ctx.Users.Add(Seed.Regular(email: "user@x.com"));
            ctx.SaveChanges();

            var user = ctx.Users.Single();
            var svc = new AdminServices(ctx);

            var ok = svc.DeleteAdmin(user.Id);

            ok.Should().BeFalse("should not delete regular users via admin delete");
        }
        finally { conn.Dispose(); }
    }

    [Fact]
    public void DeleteAdmin_Removes_Admin_From_Database()
    {
        var (ctx, conn) = TestDbFactory.CreateSqliteInMemoryContext();
        try
        {
            ctx.Users.Add(Seed.Admin(email: "del@x.com"));
            ctx.SaveChanges();

            var admin = ctx.Users.Single();
            var svc = new AdminServices(ctx);

            var ok = svc.DeleteAdmin(admin.Id);

            ok.Should().BeTrue();
            ctx.Users.Any().Should().BeFalse("admin should be removed");
        }
        finally { conn.Dispose(); }
    }
}